version: "3.7"

services:
  redis:
    container_name: redis
    restart: always
    image: "redis:latest"
    ports:
      - "6379:6379"

  mongo:
    container_name: mongo
    restart: always
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./db/:/data/db

  api:
    container_name: api
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "server"
    ports:
      - "3001:3001"
      - "3002:3002"
    links:
      - mongo
      - redis

  ui:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ui"
    restart: always
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
